name: 'PR/Push to master'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o /usr/local/bin/goss
          sudo chmod +rx /usr/local/bin/goss

      - name: Build the image
        run: "make all-ci"

      - uses: actions/upload-artifact@v2
        with:
          name: Test results (JUnit)
          path: validate_results.junit.xml
